os: linux
dist: bionic
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - clang-9
compiler: 
  - g++
  - clang
env:
  - "CC=gcc-9 CXX=g++-9"
script: ./currentBuildCommand.sh
before_install:
# Download, make and install SDL2-2.0.10 (stable)
- |
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.10.tar.gz | tar xz
  cd SDL2-2.0.8
  ./configure
  make
  sudo make install
  cd ..
  travis_retry git clone --recursive https://github.com/stuckedstudio/quick-cpp-builder.git
  cd quick-cpp-builder
  chmod +x setup.sh
  ./setup.sh
  cd ..
  cp quick-cpp-builder/build.o build.o
  chmod +x currentBuildCommand.sh