--- 
addons: 
  apt: 
    packages: 
      - g++-9
      - clang-9
    sources: 
      - ubuntu-toolchain-r-test
before_script: 
  - "if [ \"$CXX\" = \"g++\" ]; then export CXX=\"g++-9\" CC=\"gcc-9\"; fi"
  - "if [ \"$CXX\" = \"clang++\" ]; then export CXX=\"clang++-9\" CC=\"clang-9\"; fi"
  - |
      travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.10.tar.gz | tar xz
      cd SDL2-2.0.10
      ./configure
      make
      sudo make install
      cd ..
      travis_retry git clone --recursive https://github.com/stuckedstudio/quick-cpp-builder.git
      cd quick-cpp-builder
      chmod +x setup.sh
      ./setup.sh
      cd ..
      cp quick-cpp-builder/build.o build.o
      chmod +x currentBuildCommand.sh
compiler: 
  - g++
  - clang
  - gcc
dist: bionic
env: 
  - "CC=gcc-9 CXX=g++-9"
language: cpp
os: linux
script: ./currentBuildCommand.sh
