--- 
addons: 
  apt: 
    packages: 
      - g++-8
      - clang-8
      - libgcc-8-dev
      - llvm-8-dev
      - libomp-8-dev
    sources: 
      - ubuntu-toolchain-r-test
before_script: 
  - "if [ \"$CXX\" = \"g++\" ]; then export CXX=\"g++-8\" CC=\"gcc-8\"; fi"
  - "if [ \"$CXX\" = \"clang++\" ]; then export CXX=\"clang++-8\" CC=\"clang-8\"; fi"
  - |
      travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.10.tar.gz | tar xz
      cd SDL2-2.0.10
      ./configure
      make
      sudo make install
      cd ..
  - | 
      ls
      travis_retry git clone --recursive https://github.com/stuckedstudio/quick-cpp-builder.git
      cd quick-cpp-builder
      ls
  - |
      echo \"$CXX\"
      if [ \"$CXX\" = \"clang++-8\" ]; then clang++ -std=c++17 -stdlib=libc++ projectBuilder.cpp -o build.o -lc++abi ;fi
      if [ \"$CXX\" = \"g++-8\" ]; then g++ -std=c++17 projectBuilder.cpp -o build.o ;fi
  - |
      ls
      cd ..
      ls
      cp quick-cpp-builder/build.o build.o
      chmod +x currentBuildCommand.sh
compiler: 
  - g++
  - clang
dist: bionic
language: cpp
os: linux
script: ./currentBuildCommand.sh
notifications:
  email: false