language: cpp
compiler:
  - clang
  - gcc
dist: bionic
script:

before_install:
# Download, make and install SDL2-2.0.8 (stable)
- |
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
  cd SDL2-2.0.8
  ./configure
  make
  sudo make install
  cd ..
  travis_retry curl -L https://github.com/stuckedstudio/quick-cpp-builder/archive/master.zip | unzip -o master.zip
  cd master/quick-cpp-builder-master
  chmod +x setup.sh
  ./setup.sh
  cd ..
  cd ..
  cp master/quick-cpp-builder-master/build.o build.o
  chmod +x currentBuildCommand.sh
  ./currentBuildCommand.sh
