os: linux
addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- gcc-9
env:
- MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
language: cpp
compiler:
  - clang
  - gcc
dist: bionic
script: ./currentBuildCommand.sh
before_install:
# Download, make and install SDL2-2.0.8 (stable)
- |
  eval "${MATRIX_EVAL}"
  travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
  cd SDL2-2.0.8
  ./configure
  make
  sudo make install
  cd ..
  travis_retry git clone --recursive https://github.com/stuckedstudio/quick-cpp-builder.git
  cd quick-cpp-builder
  chmod +x setup.sh
  ./setup.sh
  cd ..
  cp quick-cpp-builder/build.o build.o
  chmod +x currentBuildCommand.sh